language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  slack:
    rooms:
      - secure: "iPZTc4tWhqwUxyabDX0Ahsn0ckZ7CGTSZWBFx96JKQZxIRaMBD1aoqW2GoVCkL5KuPDe9HEHj5vNcmZFy/Q+Xk4v8L75r6E2se4y1QYv3HhaFqJTg4RbhPPpV+HHvuWzVLfGXDm4F3P591oREZoKxp9w+tstg3aGiZBH5zu1vvo9Y37iRPHYA3ZdBtpSDEnWO+czWk8o2jLEOSCE0+wYwsyvWITFdWabVA0HOfc+l+tRSOYA4z2vvr1wZwzfqfaPS6aHRIJ3KE8OhwvQ15NGxxyr+9FWdw7Xd3yc3LuFp/BCQT/y6bvcPWR+hfMTXICY+03k33N7AVEFggOocsASdwZxiOoo4NVyaIQTI/a2iK5pcRJSR7zHkAPpEV4wftaOMrcHRs00K+j9AaN0/DALGtX6/Abkb2jsh15paQAbQyKJAmBxwKqlHdmiIeC1ZC4Ghvvh/t9i/rOHjIEwq562ZHVqCpuVg9fDoYDK1MAzbGRnwrFfSlMShyEiDhEYRrvF0a0XG1prqWcsVSPgNnKmGYUJT8Wmd4HK4QClbNHIHArVHm/GzAvy505nOcOPEoHYagbRdAbQ6XmbJ4FMQOse13VTT+rrmf4LbJ3IA3uHZVWu1VHTsf5UoEGgyFoCFJyx3kaEvW+rz3LKadVYlJr+lT2WCMfWbhmWTnWGVvE/UQ0="
      - secure: "jM1WYj7o1IQW8dNcqj98UqFHGCuLq9BiuWLkip7Kuh/vmv/AsZCN2WlMKPRhgOb9OnDvVm4KNm8yzY4IHVi/uUC3qWKzi8Lrz9JaQ/u9WWeJ0bb64FpwHtevbhHWP08bjfoyQJTs6nl0HSZQDDtBITVHsKycougyWPvRXn4Fn+INpBhMXk6+BlpnT5ZoZzYcgPQIp2VTLIrYd+TfA18AGj63QNuBUrr5lXELNBcpzEfk2XmpTy9/YGlJ4uUObwFhonklPoUKhT0CnWKc3VrsAwW0cHzFH2DkFJjq2G3Ol0BrSciAeqPJEC7QokE405u/0PVU0tZFLc07/1SzYqf+ZKlrMparOKpPBfjceGH9WPZp37Y2YqXH525lDtuy9v0c7cCVJdmdfU0GimPjpFyML4/KedepEm9Rsv+6Yf1RpYFpU2l7qlzHxChuJ93rNfH2EvQ0BKFFu1lhC5x9GKa3b66IqEFGOUWpvHFHhKF7ytIYejGUhOhIUyRlIY+iGJHTgG0fGIbFlnDBHnJR6v78RpBcRfy5O3+iSLUR+mftgy1k2l+1IH6r6OYr0/KM4OF3SD3pvjPMCC8/NGaRYcg+ofxDx11NVY0DPteoZaJcWfbWnGXagw75Iy1MyjlGdi645Bi0rOsxTas7BdD/EOfcnK2JKE6m40MJvZ8NyA5ltow="

cache:
  directories:
    - node_modules

before_install:
  - npm -g install npm@3

install:
  - npm install

script:
  - npm run test
  - npm run test-node
  - npm run inspect

after_success:
  - bash <(curl -s https://codecov.io/bash)
