language: node_js
node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

before_install:
  - npm -g install npm@3

install:
  - npm install

script:
  - node_modules/.bin/jest --config jest-node.json
  - node_modules/.bin/jest --config jest-jsdom.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
