language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  slack:
    rooms:

      # engineering-frontend
      - secure: "hZ9nSVB7HKegww/GHG2GGhjV1yswV7nsP7HmzlBGOfymNoK/ki4wJmH+tbfKnem6Qo6nobx4nFWq+GasZlDUe8R1BpcKA1gnwiv6QgIv7X7zXL7Z8shogRdYWt4dpDUG+9hZZGDJ45QWxQveJZ1lBma1qnjHe68VIKN11bMUwL+W2a1OIF7w7J59a1iLZaX+a8aTjyRNiLmmd0rkuTpyNx+28XaRs5obv/9o4zN4JJYNL9DlfirKBOGZ9Z5j3invvYY6P+Ukg2eb1CAy8Vb/cC0oSobM6ntnaPymHqyCrt4AtK8zbx2NsdTi/5PusWolA1iFQjTxekdIPS1RBbP1EKkL/nG0IQv1EMATIgpsVbdJ19aL5dWMB2W0450jgHB4KX3Co8yBNZyVwdrUoMwh5NkeIYjOTrE/US9UgQoqzz23mgXMUxA2OyesmkdQhTzkOYEvRYwqjSjTh17nDK83P+YIHFrilLcBmCNFEW0rxcf+SD0fdaMNXI3kwR71W2X7FDqxQPWv5o3xJs+GpHOisUcO7Pb52O/ai62cDD0XMvm1jqFbVhG9iCL/xKg0AxUWX2AAHBigbWxd3P0VZhKRk+kzde5Rnb5v6bYc6yNKs8tZXMBpkwduWge8wbB66GqL27BNlwuo2bmUjRh/2p0PI8N/DShz1oDtKfZuabSki7c="
cache:
  directories:
    - $HOME/.npm

before_install: npm -g install npm@3

install: npm install

script:
  - npm run test
  - npm run test-node
  - npm run inspect

after_success: bash <(curl -s https://codecov.io/bash)
