language: node_js
node_js:
  - "4"
  - "5"
  - "6"

notifications:
  slack:
    rooms:

      # engineering-webdev
      - secure: "i1lHdVR3Qlvbyi2v7NfnuVx/VOV22/RbdQV9ufsJ7cJA88qbWl7EPOZlDUI0vUAqTcNlT5mnrY36UrhTB7vg4ifny+Okk4d87O8uvEIiefNS7YDV5qs6+j5xaCNx2V1oUa4ULTszmpTiw+9ilnqu0q61LHCkt5lPAkYnUvs3GtV76hJcFZfm4Pzrxa0EIEmAMG3srtwqJEIR9dy6pg7xLpNx30ep5N/aC9MLEPQNoQcYozyjYVNS7bOWNGQS3ccErlVjHC5e3/49QAfNVF2XgiOq4VHBzHL/8gPweqB0XII63VihbEVwqTapP6SQM9p3YBEcn/+ZSc5Q7nuZlKvxYQelKKWKYhSjq5FlfZgMzbYD71fVGYH7JrkuCng4xN2P0E+9EaEoGCD+JWuitQxY/lnTHLC7xlIbHos05Q/8p9uv8e7lwnmSmrLH0GTbgsVUD3Rtj+0nFDY00YRFPtjrGwzO9gQOGdOv1Bz0N2X2ve1NPqXw45skkq92R6yyHYaXmOZwvLNx92yd0VhJWYw5T6l7jYnqDlVqM5suX25R4CQNufDFtGKcnG6AO2U+IgC7daroHW4ySjZLVLNc2UI1PHH1QEVjdXOnVFbfn29y3B66gV6801rT9IubtnsCbaTe4h/Jj2uCluaCLMBoss2g3UkoSYnI0IOMOzCjNYnkKoU="
cache:
  directories:
    - $HOME/.npm

before_install: npm -g install npm@3

install: npm install

script:
  - npm run test
  - npm run test-node
  - npm run inspect

after_success: bash <(curl -s https://codecov.io/bash)
